import type { Metadata } from "next";
import { Geist, Geist_Mono, Aladin, Road_Rage, EB_Garamond, Montserrat, Cinzel } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "@/context/AuthContext"; // Use authprovider to wrap the app (for all pages)

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const cinzel = Cinzel({
  variable: "--font-cinzel",
  subsets: ["latin"],
  weight: "500", 
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const roadRage = Road_Rage({
  variable: "--font-road-rage",
  subsets: ["latin"],
  weight: "400",
});

const aladin = Aladin({
  variable: "--font-aladin",
  subsets: ["latin"],
  weight: "400",
});

const ebGaramond = EB_Garamond({
  variable: "--font-eb-garamond",
  subsets: ["latin"],
  weight: "400",
});

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Phadderistspelet",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${aladin.variable} ${roadRage.variable} ${ebGaramond.variable} ${montserrat.variable} antialiased`}
      >
        {/*Wrap the app with AuthProvider. Every page will have access to the auth context */}
        <AuthProvider> 
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
